name    'cumulus-netdev-stdlib'
version '0.0.1'
source 'UNKNOWN'
author 'Sergey Sudakovich and Cumulus Netowrks Contributors'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

dependency 'netdevops/netdev_stdlib', '>= 1.0.0'